info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  app:
    uploadDir: 'uploads'
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  views:
    json:
      default:
        deep: true
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
  controllers:
    defaultScope: singleton
    upload:
      maxFileSize: 10485760
      maxRequestSize: 10485760
dataSource:
    pooled: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: ''
    dbCreate: update
    url: jdbc:mysql://localhost:3306/zajezdy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
hibernate:
  show_sql: false
  format_sql: false
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false